"use client";

import { CalendarDays, CheckCircle2, ChevronRight, Heart, MapPin, Search, ShieldCheck, Sparkles, Ticket, TrendingUp, Users } from "lucide-react";
import Image from "next/image";
import { useMemo, useState } from "react";
import { categories, events, type EventCategory, type EventListing } from "@/lib/events";

const stats = [
  { label: "Verified tickets", value: "2.4M+" },
  { label: "Cities covered", value: "180" },
  { label: "Avg checkout", value: "72 sec" }
];

function EventCard({ event, onSelect }: { event: EventListing; onSelect: (event: EventListing) => void }) {
  return (
    <article className="group overflow-hidden rounded-[8px] bg-white shadow-soft ring-1 ring-black/5">
      <div className="relative aspect-[4/3] overflow-hidden">
        <Image src={event.image} alt={event.title} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover transition duration-500 group-hover:scale-105" />
        <button className="absolute right-4 top-4 grid h-10 w-10 place-items-center rounded-full bg-white/90 text-ink shadow-lg" aria-label={`Save ${event.title}`}><Heart className="h-5 w-5" /></button>
      </div>
      <div className="space-y-4 p-5">
        <div className="flex items-center justify-between gap-3 text-sm font-semibold text-ink/60"><span style={{ color: event.accent }}>{event.category}</span><span>{event.date}</span></div>
        <div><h3 className="text-xl font-black leading-tight text-ink">{event.title}</h3><p className="mt-2 flex items-center gap-2 text-sm font-medium text-ink/60"><MapPin className="h-4 w-4" />{event.venue} · {event.city}</p></div>
        <div className="flex items-center justify-between border-t border-black/10 pt-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-ink/45">From</p><p className="text-2xl font-black">${event.price}</p></div><button onClick={() => onSelect(event)} className="inline-flex h-11 items-center gap-2 rounded-[8px] bg-ink px-4 text-sm font-bold text-white transition hover:bg-pulse">Get tickets <ChevronRight className="h-4 w-4" /></button></div>
      </div>
    </article>
  );
}

export default function Home() {
  const [activeCategory, setActiveCategory] = useState<EventCategory | "All">("All");
  const [query, setQuery] = useState("");
  const [selectedEvent, setSelectedEvent] = useState<EventListing>(events[0]);
  const visibleEvents = useMemo(() => events.filter((event) => (activeCategory === "All" || event.category === activeCategory) && `${event.title} ${event.category} ${event.venue} ${event.city}`.toLowerCase().includes(query.toLowerCase())), [activeCategory, query]);

  return (
    <main className="min-h-screen overflow-hidden">
      <header className="fixed left-0 right-0 top-0 z-50 border-b border-black/10 bg-white/88 backdrop-blur-xl"><nav className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8"><a href="#" className="flex items-center gap-3 text-xl font-black tracking-tight"><span className="grid h-10 w-10 place-items-center rounded-[8px] bg-ink text-white"><Ticket className="h-5 w-5" /></span>PulsePass</a><div className="hidden items-center gap-7 text-sm font-bold text-ink/68 md:flex"><a href="#events">Explore Events</a><a href="#nearby">Near You</a><a href="#sell">Sell Tickets</a></div><div className="flex items-center gap-3"><button className="hidden rounded-[8px] px-4 py-2 text-sm font-bold text-ink ring-1 ring-black/12 sm:block">Sign in</button><button className="rounded-[8px] bg-pulse px-4 py-2 text-sm font-bold text-white shadow-lg shadow-blue-600/25">Sell Tickets</button></div></nav></header>
      <section className="relative bg-white pt-28"><div className="mx-auto grid max-w-7xl gap-10 px-5 pb-12 pt-10 lg:grid-cols-[1fr_0.92fr] lg:px-8 lg:pb-20"><div className="flex flex-col justify-center"><h1 className="max-w-3xl text-5xl font-black leading-[0.96] tracking-normal text-ink sm:text-7xl lg:text-8xl">Find your next live moment</h1><p className="mt-6 max-w-2xl text-lg font-medium leading-8 text-ink/64">Discover verified tickets for concerts, sports, comedy, festivals, and theater with fast checkout and clear pricing.</p><div className="mt-8 rounded-[8px] bg-white p-3 shadow-soft ring-1 ring-black/8"><div className="grid gap-3 md:grid-cols-[1fr_auto_auto]"><label className="flex h-14 items-center gap-3 rounded-[8px] bg-cloud px-4"><Search className="h-5 w-5 text-ink/45" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search artists, teams, venues, cities" className="w-full bg-transparent text-base font-semibold outline-none placeholder:text-ink/40" /></label><button className="inline-flex h-14 items-center justify-center gap-2 rounded-[8px] bg-ink px-5 font-bold text-white"><CalendarDays className="h-5 w-5" />This weekend</button><button className="inline-flex h-14 items-center justify-center rounded-[8px] bg-pulse px-6 font-bold text-white">Explore Events</button></div></div><div className="mt-8 grid grid-cols-3 gap-4">{stats.map((stat) => <div key={stat.label} className="border-l-2 border-ink/12 pl-4"><p className="text-2xl font-black">{stat.value}</p><p className="mt-1 text-sm font-semibold text-ink/52">{stat.label}</p></div>)}</div></div><div className="relative min-h-[520px]"><div className="absolute inset-0 rounded-[8px] bg-ink" /><Image src="https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?auto=format&fit=crop&w=1400&q=80" alt="Concert crowd at a live event" fill priority className="rounded-[8px] object-cover opacity-85" /><div className="absolute inset-x-6 bottom-6 rounded-[8px] bg-white p-5 shadow-soft"><p className="text-sm font-bold text-coral">Trending Now</p><h2 className="mt-1 text-2xl font-black">Nova Lane World Tour</h2><p className="mt-2 text-sm font-semibold text-ink/58">SoFi Stadium · Jul 18 · 8:00 PM</p></div></div></div></section>
      <section id="events" className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><h2 className="text-4xl font-black tracking-normal">Trending Now</h2><p className="mt-3 max-w-xl text-base font-medium leading-7 text-ink/58">Fresh drops, last-minute seats, and local favorites with transparent fees before checkout.</p></div><div className="flex flex-wrap gap-2">{(["All", ...categories] as const).map((category) => <button key={category} onClick={() => setActiveCategory(category)} className={`rounded-[8px] px-4 py-3 text-sm font-bold transition ${activeCategory === category ? "bg-ink text-white" : "bg-white text-ink ring-1 ring-black/10 hover:ring-ink/25"}`}>{category}</button>)}</div></div><div className="mt-9 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{visibleEvents.map((event) => <EventCard key={event.id} event={event} onSelect={setSelectedEvent} />)}</div></section>
      <section id="nearby" className="bg-ink py-16 text-white"><div className="mx-auto grid max-w-7xl gap-8 px-5 lg:grid-cols-[0.9fr_1.1fr] lg:px-8"><div><h2 className="text-4xl font-black">Near You</h2><p className="mt-4 text-lg font-medium leading-8 text-white/62">PulsePass highlights live inventory, venue policies, parking notes, and age restrictions before you buy.</p><div className="mt-8 grid gap-4">{[["Verified entry", ShieldCheck], ["Smart recommendations", Sparkles], ["Live inventory", TrendingUp]].map(([label, Icon]) => <div key={String(label)} className="flex items-center gap-3 rounded-[8px] bg-white/8 p-4 ring-1 ring-white/10"><Icon className="h-5 w-5 text-mint" /><span className="font-bold">{String(label)}</span></div>)}</div></div><div className="rounded-[8px] bg-white p-5 text-ink shadow-soft"><div className="flex flex-col gap-5 md:flex-row"><div className="relative min-h-[260px] overflow-hidden rounded-[8px] md:w-1/2"><Image src={selectedEvent.image} alt={selectedEvent.title} fill className="object-cover" /></div><div className="flex flex-1 flex-col justify-between"><div><p className="font-bold" style={{ color: selectedEvent.accent }}>{selectedEvent.category}</p><h3 className="mt-2 text-3xl font-black leading-tight">{selectedEvent.title}</h3><p className="mt-3 text-sm font-semibold text-ink/58">{selectedEvent.venue} · {selectedEvent.city}</p></div><div className="mt-8 space-y-3">{["Mobile QR tickets", "Refund request support", "PDF receipt after checkout"].map((feature) => <div key={feature} className="flex items-center gap-3 text-sm font-bold"><CheckCircle2 className="h-5 w-5 text-mint" />{feature}</div>)}</div><div className="mt-8 flex items-center justify-between rounded-[8px] bg-cloud p-4"><div><p className="text-sm font-bold text-ink/52">{selectedEvent.date} · {selectedEvent.time}</p><p className="text-2xl font-black">2 tickets · ${selectedEvent.price * 2}</p></div><button className="rounded-[8px] bg-pulse px-5 py-3 text-sm font-bold text-white">Reserve</button></div></div></div></div></div></section>
      <section id="sell" className="mx-auto grid max-w-7xl gap-8 px-5 py-16 lg:grid-cols-3 lg:px-8">{[["Create an event", "Upload images, add ticket tiers, set capacity, and publish in minutes.", Ticket], ["Track sales", "See revenue, customers, redemptions, coupons, and refund requests.", Users], ["Protect every order", "Role permissions, audit logs, rate limits, and verified delivery.", ShieldCheck]].map(([title, body, Icon]) => <div key={String(title)} className="rounded-[8px] bg-white p-6 shadow-soft ring-1 ring-black/5"><Icon className="h-8 w-8 text-pulse" /><h3 className="mt-5 text-2xl font-black">{String(title)}</h3><p className="mt-3 text-base font-medium leading-7 text-ink/58">{String(body)}</p></div>)}</section>
      <footer className="border-t border-black/10 bg-white px-5 py-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 md:flex-row md:items-center"><div><p className="text-xl font-black">PulsePass</p><p className="mt-1 text-sm font-semibold text-ink/52">Concerts · Sports · Comedy · Festivals · Theater</p></div><form className="flex w-full max-w-md gap-2" onSubmit={(event) => event.preventDefault()}><input className="h-12 min-w-0 flex-1 rounded-[8px] bg-cloud px-4 text-sm font-semibold outline-none ring-1 ring-black/8" placeholder="Email for event drops" type="email" /><button className="h-12 rounded-[8px] bg-ink px-5 text-sm font-bold text-white">Join</button></form></div></footer>
    </main>
  );
}
